version: '3.8'

services:
  backup-service:
    build: .
    container_name: coolify-backups
    environment:
      # These will pull from Coolify's environment variables
      - DOCUSEAL_CONTAINER=${DOCUSEAL_CONTAINER}
      - DOCUSEAL_USER=${DOCUSEAL_USER}
      - DOCUSEAL_DB=${DOCUSEAL_DB}
      - N8N_CONTAINER=${N8N_CONTAINER}
      - N8N_USER=${N8N_USER}
      - N8N_DB=${N8N_DB}
    volumes:
      # Docker socket access for executing commands in other containers
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Persistent storage for backups
      - backup-data:/backups
      # Log storage
      - backup-logs:/var/log
    restart: unless-stopped
    networks:
      - coolify

volumes:
  backup-data:
    driver: local
  backup-logs:
    driver: local

networks:
  coolify:
    external: true
